### ISSUE TITLE
thank you so much for this

### ISSUE THREAD

**Issue by shuantsu** [valryon/flipon-tiny#2]
I just want to leave my "thank you" here.
I bought the game yesterday and had so much fun playing it. I love puyo puyo tetris and have played a similar game to this before.

Everything about your game is marvelous, the engine, the story mode and the soundtrack.
I want to share the game experience with my friends by playing it with them.

Then I found this. Again, I can't thank you enough for making this open-source.

But I can't find anything more than this. Is there a complete experience based on this open source project?
I'm looking forward on this.

Best of luck

**Comment by valryon** [comment]
Thanks a lot ❤️
I don’t anything has been done with the Flipon engine yet. 
Not surprising because it lacks many things very important for a full release but still.
Have a look at Super Plexis or Panel Attack if you want more Panel de pon games 🙂

**Comment by shuantsu** [comment]
I managed to run the game on unity, but I'm not very experienced with it.
thanks! I'll take a look.
