### ISSUE TITLE
Spelling mistake in campaign

### ISSUE THREAD

**Issue by chipnetics** [valryon/flipon-tiny#3]
Hi there... first off, this game on Switch is phenomenal. What an outstanding step up from Tetris Attack. I played both games back to back and Tetris Attack feels so primitive in comparison. Thanks for all your hard work, this game is worth every penny and quite underrated.

I did notice on the campaign mode, I think on the 2nd planet, the word "grandpa" was misspelled as "granpa" in a few of the dialogs (I think 3 times). This is in 2.0.0 release.

Just thought I'd put it on your radar. Thanks!

**Comment by valryon** [comment]
Hello!
Thanks a lot for your message and your feedback <3
I'll check those typos ASAP!
